name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Install dependencies with frozen lockfile using npx
      - name: Install dependencies (frozen lockfile)
        run: npx pnpm install --frozen-lockfile

      # Build the project using npx
      - name: Build the project
        run: pnpm build

      # Create a release (if tagged) using npx
      - name: Release using GitHub Actions
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npx actions/create-release@v1 \
            --tag_name=${{ github.ref_name }} \
            --release_name=${{ github.ref_name }} \
            --draft=false \
            --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Deploy step (placeholder)
      - name: Deploy the application
        run: echo "Deploy steps go here"
